---
name: Zola on GitHub Pages

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Important: disable default token

      # 2️⃣ Determine branch-specific variables
      - name: Set deploy branch
        id: vars
        run: |
          if [ "${GITHUB_REF#refs/heads/}" = "main" ]; then
            echo "PAGES_BRANCH=cf-pages" >> $GITHUB_ENV
          else
            echo "PAGES_BRANCH=preview" >> $GITHUB_ENV
          fi

      - name: Deploy to GitHub Pages
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_DIR: public  # Adjust if your build dir is different
          PAGES_BRANCH: ${{ env.PAGES_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use personal access token
